### ISSUE TITLE
License Information

### ISSUE THREAD

**Issue by mseddon** [kripken/Relooper#3]
I've implemented a source-port of this algorithm which I would like to release as part of larger project. I know that this project has been migrated into https://github.com/kripken/emscripten-fastcomp, so I could obviously use the LLVM license there, but I wonder if there is a different license that you would like to apply to *this* repository that will better let me credit you as the original author, since I am not using any other component of llvm.

Do you have any preference or advice here?

I also have a clear banner at the top of the file pointing to this repository indicating this is a direct source port, so it should be clear it's derivative work.

**Comment by kripken** [comment]
The Emscripten license is correct for this repo, that is: MIT and LLVM.

Note that a newer port, with some improvements, is in Binaryen: https://github.com/WebAssembly/binaryen/blob/master/src/cfg/Relooper.h

Curious to hear about your project, btw, when you release it :smile:

**Comment by mseddon** [comment]
Ah, thanks, then I shall use that one- and thanks for pointing me to the updated source, I shall try and incorporate them too. I shall @ you on twitter when I release it :)

Great little algorithm btw, but I confess I had to look at the source code, since I was struggling to clean-room it from the paper.  Horay for open source!
